# Generated by Django 5.2.1 on 2025-06-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["id"],
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
    ]
