# Generated by Django 5.2.1 on 2025-07-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
